#include <iostream> // THIS CLASS IS RESPONSIBLE FOR DOING I/O OPERATIONS

IOSTREAM ---- ISTREAM + OSTREAM

ISTREAM --- CIN (ASCII CHARACTERS (1 BYTE))

OSTREAM --- COUT , CERR , CLOG (ASCII CHARACTERS (1 BYTE))

WCIN (FOR UNICODE (2 BYTE))
WCOUT , WCERR , WCLOG (FOR UNICODE (2 BYTE))

int main(){
    return 0;
}